### ISSUE TITLE
Stack is not animating after swipe the first two cards

### ISSUE THREAD

**Issue by mariovillamizar** [webraptor/react-native-deck-swiper#59] opened 2021-09-11 15:40 UTC
Hey @webraptor thank you for your effort trying to keep this library alive.
I found a weird bug where the stack stops animating (zooming the next cards) after swipe the first two cards.
Take a look to this video:
https://user-images.githubusercontent.com/10704258/132953264-65a11e59-19c2-4334-badb-e1a15bc662d7.mp4

**Comment by tichpla** [comment] 2021-09-15 08:10
Hey @webraptor & @mariovillamizar I have the exact same bug as you have!

**Comment by aanikid** [comment] 2021-09-24 11:48
hello guys, same issue here 😢

**Comment by DiegoBM** [comment] 2021-09-30 23:20
Unfortunately chances are this repo is not maintained either. Same error by the way, seems to come all the way back from the original repository

**Comment by webraptor** [comment] 2021-10-01 07:52
@DiegoBM if you fix the issue, please open a PR and it will be reviewed / merged. Thanks

**Comment by DiegoBM** [comment] 2021-10-01 15:29
@webraptor after checking it's internals I have decided that I won't be using this component. I'll probably create a new one if I cannot find a suitable alternative.

Regarding the issue, it seems to be related to some change in react native, probably with the introduction of concurrent mode, or the new architecture. It will work all-righ in 0.63, but will stop working in 0.64. My gut feeling tells me that it might be related to this (https://github.com/facebook/react-native/commit/c6b9cc36da4f7d190d05122048aa4ada9c152b73), but I don't know for sure. Also it's probably related to some very brittle timings used in this library, because if you introduce a minor console delay it will start failing in 0.63 as well, but unfortunately I don't have the time to pinpoint the real reason. Anyhow, for those of you who want to stick with this library, the problem is that the state values for "stackPositionN" and "stackScaleN" (N being the position number for each stack card) are not being reseted or recalculated upon stack re-renders, and instead the stack render uses the animated values which might not be final, probably because now with the new architecture and the scheduled concurrent mode, react does not render in a deterministic way, but that's just my guess, I might be wrong. In any case, you can hack your way around it if you create a function that resets those specific state values before the call to "calculateStackCardZoomStyle", then it will work again as intended (Hint: you can use "rebuildStackAnimatedValues" as reference).

Hope it helps.

**Comment by DiegoBM** [comment] 2021-10-01 15:35
For those of you who want to stick with this library, the problem is that the state values for "stackPositionN" and "stackScaleN" (N being the position number for each stack card) are not being reseted or recalculated upon stack re-renders. You can hack your way around it if you create a function that resets those specific state values before the call to "calculateStackCardZoomStyle", then it will work again as intended (Hint: you can use "rebuildStackAnimatedValues" as reference).

Hope it helps.

**Comment by mariovillamizar** [comment] 2021-10-01 20:44
@DiegoBM can you create a pull request for this fix?

**Comment by webraptor** [comment] 2022-06-23 13:03
for some reason I didn't get the notification back then.

**Comment by webraptor** [comment] 2022-06-24 10:11
pushed on npm as 2.0.6

**Closed by webraptor** 2022-06-24 10:11 UTC
